export type PortfolioProject = {
  src: string;
  title: string;
  place: string;
  type: string;
  alt: string;
  description: string;
  keywords: string;
  width: number;
  height: number;
  format: string;
};

const projectCatalog: readonly PortfolioProject[] = [
  { src: "/portfolio/horizons-drive-coolum-beach-modern-home-exterior-3d-render.webp", title: "Horizons Drive modern residence", place: "Coolum Beach, QLD", type: "Exterior visualisation", alt: "Photorealistic exterior 3D render of a modern black-clad home with native landscaping on Horizons Drive, Coolum Beach", description: "Architectural visualisation of a contemporary single-storey residence in Coolum Beach, featuring a dark vertical-clad facade, stone chimney and landscaped garden.", keywords: "Coolum Beach 3D render, modern home exterior render, residential architectural visualisation, house facade rendering, Queensland property CGI", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/penguins-head-modern-kitchen-interior-3d-render.jpg", title: "Penguins Head modern kitchen", place: "Culburra Beach, NSW", type: "Interior visualisation", alt: "Photorealistic 3D render of a warm contemporary kitchen with a curved timber island, feature tile splashback and pendant lighting at Penguins Head", description: "High-resolution kitchen interior visualisation featuring a curved fluted-timber island, pale stone benchtop, detailed cabinetry, patterned splashback and warm architectural lighting.", keywords: "Penguins Head kitchen render, kitchen interior 3D rendering, residential interior visualisation, timber kitchen CGI, architectural rendering NSW", width: 2048, height: 1536, format: "image/jpeg" },
  { src: "/portfolio/paddington-charteris-street-luxury-living-interior-3d-render.webp", title: "Charteris Street luxury living", place: "Paddington, QLD", type: "Interior visualisation", alt: "Photorealistic 3D render of a luxury open-plan living, dining and kitchen interior on Charteris Street, Paddington, with full-height glazing and city views", description: "High-end architectural interior visualisation for Charteris Street, Paddington, featuring a refined neutral living room, open-plan dining and kitchen spaces, full-height glazing, terrace and elevated city outlook.", keywords: "Charteris Street Paddington, Paddington interior 3D render, luxury living room visualisation, open-plan interior rendering, residential property CGI Brisbane, architectural visualisation Queensland", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/penrith-industrial-units-frontage-3d-render.webp", title: "Penrith industrial units", place: "Penrith, NSW", type: "Commercial visualisation", alt: "Commercial exterior 3D render of contemporary industrial units with glazed frontages, loading access, tenant signage and landscaped street presentation in Penrith", description: "High-resolution commercial architectural visualisation of a Penrith industrial development, presenting modern warehouse units, brick and metal cladding, customer entries, vehicles and landscaping.", keywords: "Penrith industrial 3D render, warehouse visualisation, commercial property CGI, industrial units rendering, architectural visualisation NSW", width: 2048, height: 1152, format: "image/webp" },
  { src: "/portfolio/cowdroy-avenue-cammeray-waterfront-living-3d-render.jpg", title: "Cowdroy Avenue waterfront living", place: "Cammeray, NSW", type: "Interior visualisation", alt: "Photorealistic 3D render of a luxury waterfront living room on Cowdroy Avenue, Cammeray, with full-height glazing and harbour views", description: "Luxury residential interior visualisation featuring a refined open-plan living room, fireplace, contemporary furniture, full-height glazing and a panoramic waterfront outlook in Cammeray.", keywords: "Cowdroy Avenue Cammeray, waterfront living room render, luxury interior 3D rendering, harbour view visualisation, residential CGI Sydney", width: 1500, height: 844, format: "image/jpeg" },
  { src: "/portfolio/jubilee-avenue-ulladulla-townhouses-exterior-3d-render.webp", title: "Jubilee Avenue Townhouses", place: "Ulladulla, NSW", type: "Residential development CGI", alt: "Photorealistic exterior 3D render of contemporary three-storey townhouses at 19 Jubilee Avenue in Ulladulla with white facades, rooftop terraces and landscaped street frontage", description: "Property development visualisation for 19 Jubilee Avenue, Ulladulla, presenting contemporary multi-level townhouses with bright coastal facades, integrated garages, expansive glazing, rooftop terraces and layered streetscape landscaping.", keywords: "19 Jubilee Avenue Ulladulla, Ulladulla townhouse 3D render, townhouse exterior visualisation, residential development CGI NSW, coastal property rendering, architectural visualisation South Coast", width: 1600, height: 1200, format: "image/webp" },
] as const;

// The homepage owns its selection. Service pages receive separate arrays below,
// so changing a deeper page's selection cannot change the homepage selection.
export const projects: readonly PortfolioProject[] = projectCatalog.map((project) => ({ ...project }));

const independentSelection = () => projectCatalog.map((project) => ({ ...project }));

const residentialProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/S42395-81-RAVEN-STREET-CAMP-HILL-QLD-4152-Interiors-View-1-LDK-1-.webp", title: "Raven Street Living, Dining & Kitchen", place: "Camp Hill, QLD", type: "Luxury residential interior", alt: "Photorealistic residential 3D render of the living, dining and kitchen interior at 81 Raven Street, Camp Hill, with stone joinery and courtyard glazing", description: "Luxury residential interior visualisation for 81 Raven Street, Camp Hill, presenting connected living, dining and kitchen spaces, statement stone, timber detailing and full-height courtyard glazing.", keywords: "81 Raven Street Camp Hill, residential 3D rendering Brisbane, luxury interior render, living dining kitchen CGI, house visualisation Queensland", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/dromana-parade-safety-beach-master-bedroom-3d-render.webp", title: "Dromana Parade Master Bedroom", place: "Safety Beach, VIC", type: "Bedroom 3D render", alt: "Photorealistic residential 3D render of a warm neutral master bedroom on Dromana Parade, Safety Beach, with soft daylight and timber furniture", description: "Master bedroom visualisation for Dromana Parade, Safety Beach, communicating the calm neutral palette, vertical wall detailing, furniture, lighting and generous natural light.", keywords: "Dromana Parade Safety Beach, bedroom 3D render Melbourne, residential interior visualisation, master bedroom CGI, home rendering Victoria", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/rutland-street-niddrie-modern-kitchen-3d-render.webp", title: "Rutland Street Modern Kitchen", place: "Niddrie, VIC", type: "Kitchen 3D render", alt: "Photorealistic residential 3D render of a modern timber and stone kitchen on Rutland Street, Niddrie, with a large island and garden-facing windows", description: "Modern kitchen visualisation for Rutland Street, Niddrie, featuring pale timber cabinetry, stone benchtops, integrated appliances, a generous island and natural daylight.", keywords: "Rutland Street Niddrie, kitchen 3D render Melbourne, residential rendering Victoria, timber kitchen visualisation, house interior CGI", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/B23949-3-WALLOON-HIGHLANDS-MANLY-279-KINGBURY-Interiors-_KITCHEN-1-.webp", title: "Walloon Highlands Kitchen & Dining", place: "Walloon, QLD", type: "Kitchen and dining render", alt: "Photorealistic residential 3D render of the Kingbury kitchen and dining interior at Walloon Highlands with warm timber furniture and white cabinetry", description: "Kitchen and dining visualisation for the Kingbury home at Walloon Highlands, presenting family-scale spaces, detailed cabinetry, woven furniture and warm natural light.", keywords: "Walloon Highlands Kingbury, kitchen dining 3D render Queensland, residential interior visualisation, new home CGI Brisbane, house rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/S41857-PRIVATE-RESIDENCE-Interiors-_V4_BATHROOM-1.webp", title: "Private Residence Bathroom", place: "Australia", type: "Bathroom 3D render", alt: "Photorealistic residential 3D render of a warm contemporary bathroom with tiled bath, walk-in shower, timber vanity and terrazzo floor", description: "Contemporary bathroom visualisation featuring a built-in tiled bath, textured shower screen, twin timber vanity, terrazzo flooring and carefully layered natural and architectural light.", keywords: "bathroom 3D render Australia, residential bathroom visualisation, timber vanity CGI, interior architectural rendering, luxury home bathroom", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/B24035-24-26-WELCH-STREET-SOUTHPORT-Exteriors-260702.webp", title: "Welch Street Rooftop Pool", place: "Southport, QLD", type: "Residential amenity render", alt: "Photorealistic residential 3D render of a rooftop infinity pool and landscaped terrace at 24–26 Welch Street, Southport", description: "High-rise residential amenity visualisation for 24–26 Welch Street, Southport, presenting a rooftop infinity pool, sunken lounge, planting and panoramic urban outlook.", keywords: "24 26 Welch Street Southport, rooftop pool 3D render, apartment amenity visualisation Gold Coast, residential development CGI Queensland, property rendering", width: 1600, height: 1000, format: "image/webp" },
  { src: "/portfolio/S42385-COASTLINE-STUDIOS-Interiors-Big-Verve-Wellness.webp", title: "Coastline Studios Wellness Space", place: "Australia", type: "Residential wellness render", alt: "Photorealistic residential 3D render of a private wellness space with timber sauna, cold plunge, home gym and landscaped garden outlook", description: "Residential wellness visualisation for Coastline Studios, combining a timber sauna and plunge area, home gym, sheltered deck and native landscape within one connected retreat.", keywords: "Coastline Studios wellness render, home gym 3D visualisation, residential sauna CGI, private wellness space rendering, Australian home visualisation", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/eastridge-coolum-living-room-3d-render.webp", title: "Eastridge Coolum Living Room", place: "Coolum Beach, QLD", type: "Living room 3D render", alt: "Photorealistic residential 3D render of the Eastridge living room in Coolum Beach with warm timber joinery, soft neutral furniture and abundant natural light", description: "Residential living-room visualisation for Eastridge in Coolum Beach, presenting custom dark-timber entertainment joinery, a relaxed neutral lounge setting, timber flooring and soft coastal daylight.", keywords: "Eastridge Coolum living room, Coolum Beach 3D render, residential interior visualisation Queensland, living room CGI Sunshine Coast, home rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/union-street-windsor-modern-residence-exterior-3d-render.webp", title: "Union Street Modern Residence", place: "Windsor, VIC", type: "Residential exterior render", alt: "Photorealistic exterior 3D render of a contemporary two-storey residence at 35 Union Street, Windsor, with projecting window forms, timber screening and native landscaping", description: "Residential exterior visualisation for 35 Union Street, Windsor, presenting the sculptural two-storey architecture, deep-framed glazing, vertical timber screening, secure frontage and layered native garden.", keywords: "35 Union Street Windsor, modern residence 3D render, residential exterior visualisation Melbourne, house facade CGI Victoria, architectural rendering Australia", width: 1600, height: 1000, format: "image/webp" },
  { src: "/portfolio/jubilee-avenue-ulladulla-townhouses-exterior-view-3d-render.webp", title: "Jubilee Avenue Townhouses", place: "Ulladulla, NSW", type: "Townhouse development render", alt: "Photorealistic residential 3D render of contemporary three-storey townhouses at 19 Jubilee Avenue, Ulladulla, viewed across landscaped parkland", description: "Residential development visualisation for 19 Jubilee Avenue, Ulladulla, showing a coordinated row of contemporary multi-level townhouses with rooftop terraces, balconies, integrated garages and generous landscape.", keywords: "19 Jubilee Avenue Ulladulla, Ulladulla townhouse 3D render, residential development visualisation NSW, townhouse exterior CGI South Coast, property marketing rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/morrisons-avenue-mount-martha-pool-terrace-3d-render.webp", title: "Morrisons Avenue Pool Terrace", place: "Mount Martha, VIC", type: "Pool and alfresco render", alt: "Photorealistic residential 3D render of a pool terrace and covered alfresco area at 35 Morrisons Avenue, Mount Martha, with timber decking and garden outlook", description: "Residential pool and alfresco visualisation for 35 Morrisons Avenue, Mount Martha, showing the swimming pool, timber sun deck, outdoor dining and kitchen, stone detailing and seamless connection to the home interior.", keywords: "35 Morrisons Avenue Mount Martha, pool 3D render Victoria, alfresco visualisation Mornington Peninsula, residential exterior CGI Melbourne, backyard rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/ijong-street-braddon-townhouses-exterior-3d-render.webp", title: "Ijong Street Townhouses", place: "Braddon, ACT", type: "Townhouse exterior render", alt: "Photorealistic residential 3D render of contemporary dark-brick townhouses at 40 Ijong Street, Braddon, with arched windows and landscaped frontage", description: "Townhouse exterior visualisation for 40 Ijong Street, Braddon, presenting the dark brick and metal facade, arched ground-floor windows, private entries, warm interior lighting and established street trees.", keywords: "40 Ijong Street Braddon, Braddon townhouse 3D render, residential development visualisation Canberra, townhouse exterior CGI ACT, architectural rendering Australia", width: 1600, height: 1200, format: "image/webp" },
];

const commercialProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/office-breakout-room-interior-3d-render.webp", title: "City Office Breakout Room", place: "Melbourne, VIC", type: "Office interior render", alt: "Photorealistic commercial 3D render of a light-filled Melbourne office breakout room with communal tables, kitchen facilities, city views and indoor planting", description: "Commercial office interior visualisation presenting a bright staff breakout area with communal work and dining tables, integrated kitchen facilities, timber finishes, planting and expansive Melbourne city views.", keywords: "Melbourne office breakout room, commercial 3D rendering Australia, office interior visualisation, workplace fit out CGI Victoria, architectural rendering Melbourne", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/south-jerrabomberra-town-centre-restaurant-interior-3d-render.webp", title: "South Jerrabomberra Restaurant", place: "South Jerrabomberra, NSW", type: "Hospitality interior render", alt: "Photorealistic commercial 3D render of a busy restaurant tenancy at South Jerrabomberra Town Centre with timber dining furniture, pendant lights and wine display", description: "Hospitality interior visualisation for a restaurant tenancy at South Jerrabomberra Town Centre, communicating the dining layout, ceiling treatment, feature lighting, wine display and active customer atmosphere.", keywords: "South Jerrabomberra Town Centre restaurant, hospitality 3D rendering NSW, commercial interior CGI, restaurant fit out visualisation, architectural rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/multi-storey-car-park-facade-3d-render.webp", title: "Multi-Storey Car Park", place: "Australia", type: "Commercial exterior render", alt: "Photorealistic commercial 3D render of a multi-storey car park with a pale green perforated facade, integrated wayfinding, pedestrian entry and landscaped vehicle approach", description: "Commercial infrastructure visualisation of a multi-storey car park, presenting the patterned perforated facade, integrated signage, pedestrian circulation, vehicle access and surrounding landscape.", keywords: "multi-storey car park 3D render, commercial exterior visualisation Australia, car park facade CGI, infrastructure architectural rendering, perforated facade render", width: 1600, height: 900, format: "image/webp" },
  { src: "/portfolio/teemangum-street-currumbin-gym-interior-3d-render.webp", title: "Teemangum Street Gym", place: "Currumbin, QLD", type: "Fitness interior render", alt: "Photorealistic commercial 3D render of a compact gym at 43 Teemangum Street, Currumbin, with integrated equipment storage, exercise bike and yoga area", description: "Fitness interior visualisation for 43 Teemangum Street, Currumbin, showing a carefully planned gym with timber equipment storage, strength and yoga equipment, acoustic ceiling detail and architectural lighting.", keywords: "43 Teemangum Street Currumbin, gym 3D render Gold Coast, fitness interior visualisation Queensland, commercial fit out CGI, wellness space rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/monarch-place-southport-medical-suites-reception-3d-render.webp", title: "Monarch Place Medical Suites", place: "Southport, QLD", type: "Medical reception render", alt: "Photorealistic commercial 3D render of the Monarch Place medical suites reception at 67–73 Meron Street, Southport, with waiting lounge and consultation areas", description: "Healthcare interior visualisation for Monarch Place Medical Suites in Southport, presenting the reception desk, patient waiting lounge, consultation circulation, natural light and calm material palette.", keywords: "Monarch Place Medical Suites Southport, medical reception 3D render, healthcare interior visualisation Gold Coast, commercial CGI Queensland, clinic fit out rendering", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/azzura-square-south-hedland-lobby-3d-render.webp", title: "Azzura Square Lobby", place: "South Hedland, WA", type: "Commercial lobby render", alt: "Photorealistic commercial 3D render of the Azzura Square lobby in South Hedland with sculptural lighting, curved seating and stone reception desk", description: "Commercial lobby visualisation for Azzura Square at 1–13 Colebatch Way, South Hedland, featuring a sculptural pendant installation, curved lounge seating, stone reception and refined timber detailing.", keywords: "Azzura Square South Hedland, commercial lobby 3D render WA, reception interior visualisation, property development CGI, architectural rendering Western Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/south-brunswick-recreation-centre-interior-3d-render.webp", title: "South Brunswick Recreation Centre", place: "South Brunswick", type: "Community interior render", alt: "Photorealistic commercial 3D render of the South Brunswick Recreation Centre lounge with green seating, timber screens, feature lighting and community dining spaces", description: "Recreation-centre interior visualisation presenting a generous community lounge with flexible seating, dining and social areas, integrated planting, timber screening and warm feature lighting.", keywords: "South Brunswick Recreation Centre, recreation centre 3D render, community interior visualisation, commercial architectural CGI, leisure facility rendering", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/springfield-cafe-interior-3d-render.webp", title: "Springfield Café", place: "Springfield", type: "Café interior render", alt: "Photorealistic commercial 3D render of a Springfield café interior with bakery display, upholstered banquette seating, pendant lighting and warm contemporary finishes", description: "Hospitality visualisation for a Springfield café, communicating the bakery display, counter service zone, table and banquette layout, decorative lighting and warm modern customer experience.", keywords: "Springfield cafe 3D render, hospitality interior visualisation, bakery cafe fit out CGI, commercial rendering Australia, restaurant design visualisation", width: 1600, height: 1200, format: "image/webp" },
];

const marketingFloorPlanProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/landscaped-home-2d-marketing-floor-plan.webp", title: "Landscaped Home Marketing Floor Plan", place: "Australia", type: "2D colour floor plan", alt: "Detailed coloured 2D marketing floor plan of a single-storey family home with four bedrooms, double garage, pool, alfresco area and landscaped gardens", description: "Presentation-ready 2D marketing floor plan showing a complete single-storey home, furniture, room dimensions, double garage, driveway, alfresco entertaining area, swimming pool and landscaped site context.", keywords: "2D marketing floor plan Australia, coloured house floor plan, furnished floor plan rendering, real estate floor plan, property marketing plan", width: 1600, height: 740, format: "image/webp" },
  { src: "/portfolio/platino-single-storey-coloured-floor-plan.webp", title: "Platino Single-Storey Floor Plan", place: "Australia", type: "Furnished 2D floor plan", alt: "Coloured furnished marketing floor plan for the Platino single-storey residence with four bedrooms, media room, open-plan kitchen, dining and family areas", description: "Furnished 2D marketing floor plan for the Platino residence, clearly presenting four bedrooms, bathrooms, media room, open-plan living, kitchen and dining spaces, balconies and circulation.", keywords: "Platino floor plan, single storey marketing floor plan, furnished 2D floor plan, house plan rendering Australia, property marketing floor plans", width: 1600, height: 945, format: "image/webp" },
  { src: "/portfolio/townhouse-development-3d-floor-plan.webp", title: "Townhouse Development 3D Floor Plan", place: "Australia", type: "3D development floor plan", alt: "Top-down furnished 3D marketing floor plan of a multi-townhouse development showing kitchens, bedrooms, bathrooms, living areas and integrated garages", description: "Three-dimensional development floor plan illustrating multiple connected townhouse layouts with realistic furniture, kitchens, bathrooms, living spaces, stairs and private garages.", keywords: "3D townhouse floor plan, development marketing floor plan, furnished 3D plan Australia, townhouse layout visualisation, property development floor plans", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/platino-furnished-single-storey-floor-plan.webp", title: "Platino Furnished Home Plan", place: "Australia", type: "Coloured residential floor plan", alt: "Wide coloured furnished floor plan of the Platino single-storey home with four bedrooms, media room, open-plan family living, kitchen and balcony", description: "Residential marketing plan for the Platino home, using colour, furniture and material detail to make the four-bedroom layout, open-plan living spaces, media room and outdoor areas immediately understandable.", keywords: "Platino furnished floor plan, coloured residential plan Australia, four bedroom marketing floor plan, house layout visualisation, real estate floor plan rendering", width: 1600, height: 1047, format: "image/webp" },
  { src: "/portfolio/the-nix-jindabyne-unit-9-floor-plan.webp", title: "The Nix Jindabyne Unit 9", place: "Jindabyne, NSW", type: "Landscaped sales floor plan", alt: "Coloured marketing floor plan for The Nix Jindabyne Unit 9 with three bedrooms, open-plan living, deck, landscaped garden and two parking spaces", description: "Branded sales floor plan for The Nix Jindabyne, showing a three-bedroom layout with kitchen, meals and living zones, deck, landscaped private open space, laundry, bathroom and parking.", keywords: "The Nix Jindabyne floor plan, Jindabyne property marketing plan, three bedroom floor plan NSW, coloured real estate plan, furnished 2D floor plan", width: 1600, height: 1130, format: "image/webp" },
  { src: "/portfolio/allere-west-village-apartment-u09-floor-plan.webp", title: "Allere West Village Apartment U-09", place: "West End, QLD", type: "Apartment sales floor plan", alt: "Branded marketing floor plan for Allere West Village apartment U-09 in Tower 5A with two bedrooms, two bathrooms, open-plan living and balcony", description: "Property marketing floor plan for Allere at West Village Brisbane, presenting apartment U-09 with two bedrooms, two bathrooms, open living and dining, kitchen, balcony and building location diagram.", keywords: "Allere West Village floor plan, West End apartment marketing plan, U09 Tower 5A, Brisbane real estate floor plan, two bedroom apartment layout", width: 1600, height: 1132, format: "image/webp" },
  { src: "/portfolio/the-riverly-apartment-3-marketing-floor-plan.webp", title: "The Riverly Apartment 3", place: "Australia", type: "Branded apartment floor plan", alt: "Branded marketing floor plan for The Riverly Apartment 3, Building Archer Level 1, with two bedrooms, two bathrooms, study and large landscaped terraces", description: "Branded apartment sales plan for The Riverly, combining the furnished two-bedroom layout, study, indoor and outdoor area figures, landscaped terraces, building location and project information.", keywords: "The Riverly Apartment 3 floor plan, apartment marketing plan Australia, two bedroom floor plan, property sales collateral, branded real estate plan", width: 1600, height: 1052, format: "image/webp" },
  { src: "/portfolio/double-storey-coloured-marketing-floor-plan.webp", title: "Double-Storey Coloured Floor Plan", place: "Australia", type: "Multi-level 2D floor plan", alt: "Coloured furnished marketing floor plan showing the ground and first floors of a double-storey home with four bedrooms, garage, gardens and balconies", description: "Detailed two-level marketing floor plan presenting the ground-floor living, kitchen, guest suite, garage and gardens alongside the first-floor bedrooms, bathrooms, rumpus room and balconies.", keywords: "double storey marketing floor plan, coloured 2D floor plan Australia, furnished house plan, multi level floor plan rendering, property marketing visualisation", width: 1400, height: 990, format: "image/webp" },
];

const photomontageProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/grayson-drive-scoresby-dual-occupancy-photomontage.webp", title: "Grayson Drive Dual Occupancy", place: "Scoresby, VIC", type: "Residential photomontage", alt: "Architectural photomontage of a contemporary dual-occupancy development on Grayson Drive in Scoresby integrated into the existing suburban streetscape", description: "Site-integrated residential photomontage for Grayson Drive, Scoresby, showing two coordinated single-storey homes, garages, native landscaping and their relationship to the surrounding neighbourhood.", keywords: "Grayson Drive Scoresby, dual occupancy photomontage, residential photomontage Melbourne, house development CGI Victoria, architectural visualisation Scoresby", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/pacific-avenue-tamarama-apartments-photomontage.webp", title: "Pacific Avenue Apartments", place: "Tamarama, NSW", type: "Coastal photomontage", alt: "Wide coastal architectural photomontage of a contemporary apartment building on Pacific Avenue in Tamarama integrated into the existing beachfront streetscape", description: "Coastal apartment photomontage for Pacific Avenue, Tamarama, placing the proposed multi-residential design accurately within the existing hillside neighbourhood and beachfront context.", keywords: "Pacific Avenue Tamarama, Tamarama apartment photomontage, coastal development CGI Sydney, architectural photomontage NSW, beachfront apartment visualisation", width: 2048, height: 1365, format: "image/webp" },
  { src: "/portfolio/residential-precinct-aerial-photomontage.webp", title: "Residential Precinct Aerial", place: "Australia", type: "Aerial photomontage", alt: "High-resolution aerial architectural photomontage of a contemporary residential precinct integrated into an established urban and parkland setting", description: "Large-scale aerial photomontage communicating the layout, building forms, streets, landscaping and broader urban context of a contemporary multi-residential precinct.", keywords: "residential precinct aerial photomontage, masterplan aerial CGI, townhouse development visualisation Australia, urban context rendering, property development photomontage", width: 2048, height: 1525, format: "image/webp" },
  { src: "/portfolio/penrith-industrial-development-aerial-photomontage.webp", title: "Penrith Industrial Development", place: "Penrith, NSW", type: "Industrial aerial photomontage", alt: "Aerial architectural photomontage of a large industrial development in Penrith integrated beside existing infrastructure, businesses, roads and wetlands", description: "Industrial aerial photomontage for Penrith, showing the proposed warehouse development within its real infrastructure, landscape and commercial context at golden hour.", keywords: "Penrith industrial photomontage, warehouse aerial CGI NSW, industrial development visualisation, commercial property photomontage Sydney, architectural rendering Penrith", width: 2048, height: 983, format: "image/webp" },
  { src: "/portfolio/falconer-street-southport-apartments-aerial-photomontage.webp", title: "Falconer Street Apartments", place: "Southport, QLD", type: "Apartment aerial photomontage", alt: "Aerial architectural photomontage of a contemporary apartment development at 54 Falconer Street in Southport integrated into the existing neighbourhood", description: "Property-development photomontage for 54 Falconer Street, Southport, presenting the proposed apartment building, balconies, landscaping, vehicle access and surrounding residential context.", keywords: "54 Falconer Street Southport, Southport apartment photomontage, aerial property CGI Gold Coast, apartment development visualisation Queensland, architectural rendering Southport", width: 2048, height: 1365, format: "image/webp" },
  { src: "/portfolio/geofabric-mining-aerial-photomontage.webp", title: "Geofabric Mining Landscape", place: "Australia", type: "Mining aerial photomontage", alt: "Expansive aerial photomontage of an Australian open-cut mining operation with geofabric installations, haul roads, processing infrastructure, rail and water management areas", description: "Large-scale mining and geofabric aerial visualisation communicating the proposed open-cut operation, terrain, access routes, material storage, water management and industrial infrastructure.", keywords: "mining aerial photomontage Australia, geofabric visualisation, open cut mine CGI, mining infrastructure rendering, environmental engineering photomontage", width: 2048, height: 1374, format: "image/webp" },
] as const;

const facadeProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/grevillea-crescent-swan-view-modern-home-3d-render.webp", title: "Grevillea Crescent Modern Residence", place: "Swan View, WA", type: "Facade render", alt: "Photorealistic facade 3D render of a contemporary two-storey home on Grevillea Crescent in Swan View with black cladding, warm timber and native landscaping", description: "Contemporary two-storey home facade visualisation for Grevillea Crescent, Swan View, showing the architectural form, black and timber material palette and detailed front landscaping.", keywords: "Grevillea Crescent Swan View, modern home 3D render, house facade rendering Perth, residential exterior visualisation, facade CGI Australia", width: 1300, height: 975, format: "image/webp" },
  { src: "/portfolio/double-storey-coastal-home-exterior-3d-render.webp", title: "Double Storey Home Range", place: "Australia", type: "Facade render", alt: "Photorealistic exterior 3D render of a light coastal-style double-storey home with weatherboard cladding, gabled roof and landscaped frontage", description: "Residential facade render of a double-storey coastal home, presenting its weatherboard cladding, gabled roof, entry, garage and street-facing landscape in clear daylight.", keywords: "double storey coastal home render, coastal facade 3D rendering, exterior house visualisation, builder facade CGI, Australian home render", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/collaroy-plateau-house-1a-facade-3d-render.webp", title: "Collaroy Plateau House", place: "Collaroy Plateau, NSW", type: "Facade render", alt: "Photorealistic facade 3D render of House 1A at Collaroy Plateau featuring a refined white two-storey exterior, arched window and subtropical landscaping", description: "House 1A facade visualisation for Collaroy Plateau, with detailed white exterior finishes, arched glazing, tiled roof and a fully landscaped street presentation.", keywords: "Collaroy Plateau House 1A, house facade 3D render, white home exterior CGI, residential visualisation Sydney, facade rendering NSW", width: 1300, height: 975, format: "image/webp" },
  { src: "/portfolio/casa-sol-210-home-facade-3d-render.webp", title: "Casa Sol Home Facades", place: "Australia", type: "Facade render", alt: "Photorealistic front facade 3D render of the Casa Sol 210 single-storey home with a light coastal material palette and landscaped entry", description: "Casa Sol 210 facade render presenting the single-storey design, roof form, garage, entry details, light exterior finishes and front landscaping.", keywords: "Casa Sol 210, home facade 3D render, single storey house rendering, builder facade visualisation, residential CGI Australia", width: 1300, height: 731, format: "image/webp" },
  { src: "/portfolio/bulleen-road-balwyn-north-luxury-home-3d-render.webp", title: "Bulleen Road Luxury Residence", place: "Balwyn North, VIC", type: "Facade render", alt: "Photorealistic facade 3D render of a grand luxury residence on Bulleen Road in Balwyn North with formal architecture and landscaped frontage", description: "Luxury residential facade visualisation for Bulleen Road, Balwyn North, showing the formal two-storey architecture, detailed exterior mouldings, entry gates and established landscape.", keywords: "Bulleen Road Balwyn North, luxury home 3D render, mansion facade rendering Melbourne, residential exterior CGI, architectural visualisation Victoria", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/s40902-coastline-studios-exterior-cs2-3d-render.webp", title: "Prefab Homes", place: "Australia", type: "Facade render", alt: "Photorealistic exterior 3D render of Coastline Studios CS2, a contemporary single-storey modular coastal home surrounded by native trees and landscaping", description: "S40902 Coastline Studios CS2 exterior facade visualisation featuring a low contemporary form, expansive glazing, native landscape and coastal setting.", keywords: "S40902 Coastline Studios CS2, coastline studio exterior render, modular home facade 3D rendering, coastal house CGI, Australian residential visualisation", width: 2048, height: 1152, format: "image/webp" },
] as const;

const streetscapeProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/lowry-street-elizabeth-east-homes-streetscape-3d-render.webp", title: "Lowry Street Homes", place: "Elizabeth East, SA", type: "Residential streetscape", alt: "Photorealistic streetscape 3D render of four contemporary single-storey homes on Lowry Street in Elizabeth East with landscaped frontages", description: "Residential streetscape visualisation for 1 Lowry Street, Elizabeth East, presenting four coordinated single-storey homes with varied rooflines, contemporary facades, integrated garages and layered landscaping.", keywords: "1 Lowry Street Elizabeth East, Elizabeth East homes 3D render, residential streetscape visualisation, single storey house rendering Adelaide, property development CGI South Australia, architectural rendering Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/sunshine-west-modern-townhouse-row-3d-render.webp", title: "Sunshine West Modern Townhouses", place: "Sunshine West, VIC", type: "Townhouse streetscape", alt: "Photorealistic streetscape 3D render of a row of contemporary two-storey townhouses in Sunshine West, Victoria, with gabled facades, integrated garages and landscaped frontage", description: "Residential development visualisation of a contemporary townhouse row in Sunshine West, featuring varied gabled forms, render and metal cladding, integrated garages, private entries and coordinated street landscaping.", keywords: "Sunshine West townhouse 3D render, modern townhouse row visualisation, residential streetscape CGI, townhouse development rendering Melbourne, property marketing Victoria, architectural visualisation Australia", width: 1400, height: 1050, format: "image/webp" },
  { src: "/portfolio/princes-highway-beaconsfield-townhouses-3d-render.webp", title: "Princes Highway Townhouses", place: "Beaconsfield, VIC", type: "Townhouse streetscape", alt: "Photorealistic wide-angle 3D render of contemporary townhouses on Princes Highway in Beaconsfield with mixed brick and rendered facades, front gardens and pedestrian paths", description: "Townhouse development visualisation showing the rhythm of multiple two-storey homes, coordinated facade variation, fencing, pedestrian paths and layered landscape.", keywords: "Princes Highway Beaconsfield, townhouse 3D render, residential development visualisation, townhouse streetscape CGI, property marketing Victoria", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/archer-addison-hamptons-homes-3d-render.webp", title: "Archer Addison Hamptons Homes", place: "Australia", type: "Builder range streetscape", alt: "Photorealistic 3D render of a Hamptons-style single-storey home range arranged along a landscaped Australian suburban street", description: "Builder-range visualisation showing coordinated Hamptons-inspired homes, front gardens, driveways and a clear suburban street presentation.", keywords: "Archer Addison Hamptons homes, builder range 3D render, house and land visualisation, residential streetscape rendering, Australian home marketing CGI", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/gulf-parade-south-brighton-duplex-3d-render.webp", title: "Gulf Parade Duplexes", place: "South Brighton, SA", type: "Coastal streetscape", alt: "Photorealistic streetscape 3D render of contemporary coastal duplex homes on Gulf Parade in South Brighton with curved facades and landscaped frontages", description: "Coastal duplex streetscape visualisation with curved architecture, stone and timber finishes, integrated garages and layered planting.", keywords: "Gulf Parade South Brighton, duplex 3D render, streetscape rendering Adelaide, coastal homes visualisation, residential development CGI South Australia", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/vera-apartments-queanbeyan-street-view-3d-render.webp", title: "Vera Apartments Street View", place: "Queanbeyan, NSW", type: "Urban streetscape", alt: "Photorealistic street-view 3D render of Vera Apartments with a contemporary multi-residential facade, brick podium, landscaping and active Queanbeyan streetscape", description: "Property marketing visualisation of Vera Apartments, presenting its multi-residential architecture, public realm, residents, vehicles and street activity.", keywords: "Vera Apartments Queanbeyan, apartment streetscape 3D render, multi-residential property marketing CGI, architectural rendering NSW", width: 2048, height: 1536, format: "image/webp" },
] as const;

const alfrescoBackyardProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/lawley-street-deakin-pool-courtyard-3d-render.webp", title: "Lawley Street Pool Courtyard", place: "Deakin, ACT", type: "Pool courtyard render", alt: "Photorealistic 3D render of a contemporary pool courtyard at 21 Lawley Street, Deakin, with glass fencing, sun lounges, mature landscaping and full-height glazing", description: "High-resolution alfresco and backyard visualisation for 21 Lawley Street, Deakin, presenting a refined pool courtyard, glass safety fence, outdoor lounging, architectural glazing and layered garden planting.", keywords: "21 Lawley Street Deakin, Deakin pool courtyard 3D render, luxury backyard visualisation, alfresco rendering Canberra, residential pool CGI ACT", width: 1300, height: 731, format: "image/webp" },
  { src: "/portfolio/wright-street-middle-park-pool-courtyard-3d-render.webp", title: "Wright Street Pool Courtyard", place: "Middle Park, VIC", type: "Alfresco courtyard render", alt: "Photorealistic pool and alfresco courtyard 3D render at 80 Wright Street, Middle Park, with outdoor dining, curved architecture and full-height glazing", description: "Architectural visualisation of the pool and courtyard at 80 Wright Street, Middle Park, featuring an outdoor dining terrace, curved contemporary forms, glazed living spaces and integrated landscape.", keywords: "80 Wright Street Middle Park, pool courtyard 3D render, luxury alfresco visualisation, backyard rendering Melbourne, residential exterior CGI Victoria", width: 1300, height: 813, format: "image/webp" },
  { src: "/portfolio/cupania-street-mudjimba-alfresco-pool-3d-render.webp", title: "Cupania Street Alfresco", place: "Mudjimba, QLD", type: "Covered alfresco render", alt: "Photorealistic 3D render of a covered alfresco dining area and swimming pool at 13 Cupania Street, Mudjimba, surrounded by lush tropical landscaping", description: "Residential outdoor-living visualisation for 13 Cupania Street, Mudjimba, showing a covered dining terrace, glass pool fencing, integrated barbecue and dense subtropical planting.", keywords: "13 Cupania Street Mudjimba, alfresco 3D render, covered outdoor dining visualisation, backyard pool CGI, Sunshine Coast architectural rendering Queensland", width: 1300, height: 975, format: "image/webp" },
  { src: "/portfolio/dolphins-mollymook-pool-terrace-3d-render.webp", title: "Dolphins Mollymook Pool Terrace", place: "Mollymook, NSW", type: "Hospitality pool render", alt: "Photorealistic 3D render of the Dolphins Mollymook pool terrace with striped sun lounges, umbrellas, coastal planting and resort-style landscaping", description: "Pool and outdoor amenity visualisation for Dolphins Mollymook, presenting a bright coastal terrace, swimming pool, striped furniture, shade umbrellas and layered resort planting.", keywords: "Dolphins Mollymook, pool terrace 3D render, coastal hospitality visualisation, resort pool CGI, landscape rendering South Coast NSW", width: 1300, height: 975, format: "image/webp" },
  { src: "/portfolio/wildflower-street-sunshine-beach-alfresco-pool-3d-render.webp", title: "Wildflower Street Alfresco", place: "Sunshine Beach, QLD", type: "Indoor-outdoor living render", alt: "Photorealistic alfresco and pool 3D render at 12 Wildflower Street, Sunshine Beach, with stone walls, outdoor dining, tropical landscaping and indoor-outdoor living", description: "Indoor-outdoor residential visualisation for 12 Wildflower Street, Sunshine Beach, featuring a stone-lined alfresco dining space, swimming pool, pergola lounge and tropical garden setting.", keywords: "12 Wildflower Street Sunshine Beach, alfresco pool 3D render, indoor outdoor living visualisation, luxury backyard CGI, Noosa architectural rendering Queensland", width: 1300, height: 975, format: "image/webp" },
  { src: "/portfolio/deakin-street-bentleigh-east-alfresco-3d-render.webp", title: "Deakin Street Alfresco", place: "Bentleigh East, VIC", type: "Residential alfresco render", alt: "Photorealistic 3D render of a covered backyard alfresco at 25 Deakin Street, Bentleigh East, with an outdoor kitchen, dining setting, timber pergola and landscaped lawn", description: "Residential alfresco visualisation for 25 Deakin Street, Bentleigh East, presenting a sheltered outdoor dining terrace, built-in barbecue kitchen, timber pergola, brick detailing and landscaped backyard.", keywords: "25 Deakin Street Bentleigh East, alfresco 3D render, outdoor kitchen visualisation, backyard rendering Melbourne, residential exterior CGI Victoria", width: 1300, height: 975, format: "image/webp" },
] as const;

const livingKitchenDiningProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/manning-street-mosman-park-living-kitchen-dining-3d-render.webp", title: "Manning Street Open-Plan Interior", place: "Mosman Park, WA", type: "Living, kitchen and dining render", alt: "Photorealistic 3D render of the open-plan living, kitchen and dining interior at 47A Manning Street, Mosman Park, with a fluted timber island, stone dining table and soft neutral furnishings", description: "Interior architectural visualisation for 47A Manning Street, Mosman Park, presenting a cohesive open-plan kitchen, dining and living area with warm timber detailing, pale stone surfaces and contemporary furniture.", keywords: "47A Manning Street Mosman Park, living kitchen dining 3D render, open plan interior visualisation, kitchen rendering Perth, residential interior CGI Western Australia", width: 1600, height: 1201, format: "image/webp" },
  { src: "/portfolio/raven-street-camp-hill-kitchen-3d-render.webp", title: "Raven Street Statement Kitchen", place: "Camp Hill, QLD", type: "Kitchen interior render", alt: "Photorealistic 3D render of the kitchen at 81 Raven Street, Camp Hill, featuring dramatic natural stone surfaces, warm timber cabinetry, brick columns and integrated dining", description: "High-end kitchen visualisation for 81 Raven Street, Camp Hill, showcasing richly veined stone, custom timber joinery, layered architectural lighting and the connection to the adjacent dining space.", keywords: "81 Raven Street Camp Hill, luxury kitchen 3D render, stone kitchen visualisation Brisbane, interior rendering Queensland, residential kitchen CGI", width: 1600, height: 700, format: "image/webp" },
  { src: "/portfolio/bonnin-street-reynella-open-plan-living-3d-render.webp", title: "Bonnin Street Open-Plan Living", place: "Reynella, SA", type: "Open-plan living render", alt: "Photorealistic 3D render of a bright open-plan living, dining and kitchen interior on Bonnin Street, Reynella, with pale timber cabinetry, large windows and neutral furnishings", description: "Residential interior visualisation for Bonnin Street, Reynella, showing a light-filled open-plan living, dining and kitchen arrangement with garden outlooks and a calm natural material palette.", keywords: "Bonnin Street Reynella, open plan living 3D render, kitchen dining visualisation Adelaide, residential interior CGI South Australia, interior architectural rendering", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/private-residence-open-plan-kitchen-living-3d-render.webp", title: "Private Residence Kitchen & Living", place: "Australia", type: "Indoor-outdoor interior render", alt: "Photorealistic 3D render of a private residence with a timber kitchen, stone floor, dining zone and full-height glazing opening to a landscaped pool courtyard", description: "Indoor-outdoor residential visualisation featuring a sculptural timber kitchen, central island, dining space, stone flooring and expansive glazing connecting the interior to a tropical pool landscape.", keywords: "private residence kitchen 3D render, open plan living visualisation, indoor outdoor interior CGI, timber kitchen rendering, luxury residential architectural visualisation Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/coastal-residence-living-dining-kitchen-3d-render.webp", title: "Coastal Residence Living Interior", place: "Australia", type: "Coastal interior render", alt: "Photorealistic 3D render of a coastal open-plan living, dining and kitchen interior with ocean views, curved fireplace, neutral furniture and warm natural finishes", description: "Coastal residence interior visualisation presenting an expansive living, dining and kitchen space with ocean outlooks, a feature fireplace, curved joinery and a refined sunlit material palette.", keywords: "coastal residence interior 3D render, ocean view living room visualisation, kitchen dining CGI Australia, luxury interior rendering, property marketing architectural visualisation", width: 1600, height: 720, format: "image/webp" },
  { src: "/portfolio/twin-creeks-estate-open-plan-living-3d-render.webp", title: "Twin Creeks Estate Open-Plan Living", place: "Luddenham, NSW", type: "Open-plan interior render", alt: "Photorealistic 3D render of an open-plan kitchen, dining and living interior at Twin Creeks Estate, with marble island, double-height glazing and tropical landscape views", description: "Lifestyle-led interior visualisation for Twin Creeks Estate, combining a marble kitchen, generous dining area, lounge and expansive garden-facing glazing within one connected open-plan space.", keywords: "Twin Creeks Estate Luddenham, open plan living 3D render, kitchen dining visualisation Sydney, luxury residential interior CGI NSW, architectural rendering Australia", width: 1600, height: 1200, format: "image/webp" },
] as const;

const industrialProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/tinnula-drive-jilliby-industrial-units-view-2-3d-render.webp", title: "Tinnula Drive Industrial Units", place: "Jilliby, NSW", type: "Industrial exterior render", alt: "Photorealistic exterior 3D render of contemporary industrial units on Tinnula Drive in Jilliby with red-framed glazed entries, loading access and native landscaping", description: "Industrial architectural visualisation for Tinnula Drive, Jilliby, presenting a contemporary warehouse development with clear tenant entries, loading doors, metal cladding and layered native landscaping.", keywords: "Tinnula Drive Jilliby, Jilliby industrial units 3D render, warehouse exterior visualisation, commercial property CGI NSW, industrial architectural rendering Australia", width: 2048, height: 1152, format: "image/webp" },
  { src: "/portfolio/tinnula-drive-jilliby-warehouse-interior-3d-render.webp", title: "Tinnula Drive Warehouse Interior", place: "Jilliby, NSW", type: "Warehouse interior render", alt: "Photorealistic warehouse interior 3D render on Tinnula Drive in Jilliby with pallet racking, forklift, mezzanine office, skylights and suspended lighting", description: "Warehouse interior visualisation for Tinnula Drive, Jilliby, showing storage operations, pallet racking, forklift access, a mezzanine office, structural framing and daylight from roof skylights.", keywords: "Tinnula Drive warehouse interior, Jilliby warehouse 3D render, industrial interior visualisation, logistics facility CGI, commercial rendering NSW", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/deering-street-yamba-industrial-units-exterior-3d-render.jpg", title: "Deering Street Industrial Units", place: "Yamba, NSW", type: "Industrial streetscape render", alt: "Photorealistic streetscape 3D render of industrial units at 3 Deering Street in Yamba with geometric green facades, roller doors, glazing and landscaped frontage", description: "Industrial development visualisation for 3 Deering Street, Yamba, presenting multiple warehouse units with distinctive geometric facade graphics, vehicle access and an active landscaped streetscape.", keywords: "3 Deering Street Yamba, Yamba industrial units 3D render, warehouse development visualisation, industrial streetscape CGI, commercial architectural rendering NSW", width: 2048, height: 1536, format: "image/jpeg" },
  { src: "/portfolio/reserve-court-altona-north-commercial-building-3d-render.webp", title: "Reserve Court Commercial Building", place: "Altona North, VIC", type: "Commercial exterior render", alt: "Photorealistic commercial building 3D render on Reserve Court in Altona North with a glazed office facade, warehouse wings, parking and established trees", description: "Commercial architectural visualisation for Reserve Court, Altona North, featuring a contemporary glazed office frontage, adjoining warehouse spaces, customer parking and landscaped surrounds.", keywords: "Reserve Court Altona North, commercial building 3D render, industrial office visualisation, warehouse facade CGI Melbourne, architectural rendering Victoria", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/multi-storey-car-park-facade-3d-render.webp", title: "Multi-Storey Car Park", place: "Australia", type: "Infrastructure exterior render", alt: "Photorealistic 3D render of a multi-storey car park with a perforated green facade, integrated wayfinding, pedestrian entry and landscaped vehicle approach", description: "Infrastructure visualisation of a multi-storey car park, communicating the patterned perforated facade, integrated signage, pedestrian circulation, vehicle access and surrounding landscape.", keywords: "multi-storey car park 3D render, car park facade visualisation, infrastructure CGI Australia, commercial architectural rendering, perforated facade render", width: 2048, height: 1152, format: "image/webp" },
  { src: "/portfolio/kyneton-metcalf-road-industrial-units-exterior-3d-render.webp", title: "Metcalf Road Industrial Units", place: "Kyneton, VIC", type: "Industrial exterior render", alt: "Photorealistic exterior 3D render of brick industrial units on Metcalf Road in Kyneton with double-height glazing, warehouse access and landscaped parking", description: "Industrial unit visualisation for Metcalf Road, Kyneton, presenting brick and dark metal architecture, double-height glazed frontages, flexible warehouse interiors and landscaped parking.", keywords: "Metcalf Road Kyneton, Kyneton industrial units 3D render, warehouse exterior visualisation, commercial property CGI Victoria, industrial architectural rendering", width: 2048, height: 1536, format: "image/webp" },
] as const;

const officeFitoutProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/racv-city-club-open-workplace-3d-render.webp", title: "RACV City Club Open Workplace", place: "Melbourne, VIC", type: "Open workplace render", alt: "Photorealistic wide-angle 3D render of the RACV City Club office fit-out in Melbourne with collaborative worktables, acoustic booths and integrated planting", description: "Workplace interior visualisation for RACV City Club, presenting an open collaborative office with shared tables, acoustic booth seating, integrated planting and layered architectural lighting.", keywords: "RACV City Club office render, Melbourne office fit out 3D rendering, open workplace visualisation, commercial interior CGI Victoria, collaborative office design", width: 1920, height: 1080, format: "image/webp" },
  { src: "/portfolio/80-collins-street-melbourne-office-breakout-3d-render.webp", title: "80 Collins Street Office Breakout", place: "Melbourne, VIC", type: "Office breakout render", alt: "Photorealistic office breakout area 3D render at 80 Collins Street in Melbourne with city views, communal tables, kitchen facilities and indoor planting", description: "Office fit-out visualisation for 80 Collins Street, Melbourne, featuring a light-filled staff breakout area with communal dining, kitchen facilities, exposed services and expansive city views.", keywords: "80 Collins Street Melbourne, office breakout 3D render, workplace interior visualisation, commercial fit out CGI, Melbourne office rendering", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/office-breakout-room-interior-3d-render.webp", title: "City Office Breakout Room", place: "Melbourne, VIC", type: "Staff amenity render", alt: "Photorealistic office breakout room 3D render with timber communal tables, kitchen island, city views, natural light and indoor planting", description: "Contemporary workplace breakout-room visualisation showing flexible communal seating, a staff kitchen, timber finishes, natural light and panoramic city outlooks.", keywords: "office breakout room 3D render, staff amenity visualisation, workplace kitchen CGI, commercial interior rendering Melbourne, office fit out Australia", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/racv-city-club-boardroom-3d-render.webp", title: "RACV City Club Boardroom", place: "Melbourne, VIC", type: "Boardroom render", alt: "Photorealistic wide-angle 3D render of the RACV City Club boardroom in Melbourne with a large stone meeting table, acoustic wall panels and sculptural pendant lighting", description: "Boardroom interior visualisation for RACV City Club, featuring a generous stone conference table, integrated presentation screen, acoustic wall finishes and statement pendant lighting.", keywords: "RACV City Club boardroom, Melbourne boardroom 3D render, conference room visualisation, office fit out CGI Victoria, commercial interior rendering", width: 1920, height: 1080, format: "image/webp" },
  { src: "/portfolio/commercial-office-fitout-breakout-room-3d-render.webp", title: "Commercial Office Breakout Room", place: "Australia", type: "Breakout room render", alt: "Photorealistic commercial office breakout room 3D render with a staff kitchen, island seating, acoustic ceiling, banquettes and warm timber finishes", description: "Commercial office fit-out visualisation of a welcoming staff breakout room with a full kitchen, communal island, flexible tables, banquette seating and acoustic ceiling treatment.", keywords: "commercial office fitout render, breakout room 3D visualisation, staff kitchen CGI, workplace interior rendering Australia, office amenity design", width: 1600, height: 1200, format: "image/webp" },
  { src: "/portfolio/castlereagh-street-commercial-interior-3d-render.webp", title: "Castlereagh Street Commercial Interior", place: "Sydney, NSW", type: "Reception and breakout render", alt: "Photorealistic commercial interior 3D render on Castlereagh Street in Sydney with lounge seating, curved mesh screening, illuminated branding and collaborative spaces", description: "Commercial workplace visualisation for Castlereagh Street, Sydney, showing a distinctive arrival lounge, curved mesh partition, illuminated brand feature and connected breakout spaces.", keywords: "Castlereagh Street Sydney office render, commercial interior 3D visualisation, workplace reception CGI, office fit out rendering NSW, branded office interior", width: 1600, height: 1200, format: "image/webp" },
] as const;

const retailHospitalityProjects: readonly PortfolioProject[] = [
  { src: "/portfolio/fyshwick-automotive-showroom-interior-3d-render.webp", title: "Fyshwick Automotive Showroom", place: "Fyshwick, ACT", type: "Retail showroom render", alt: "Photorealistic 3D render of a premium automotive showroom in Fyshwick with sports cars, sculptural perforated ceiling panels, integrated lighting and full-height glazing", description: "Retail interior visualisation for an automotive showroom near Canberra Avenue and Tom Price Street, Fyshwick, presenting the display floor, customer lounge, glazing and distinctive illuminated ceiling design.", keywords: "Fyshwick automotive showroom 3D render, Canberra Avenue retail visualisation, car dealership interior CGI, showroom architectural rendering ACT, retail interior rendering Australia", width: 2048, height: 1146, format: "image/webp" },
  { src: "/portfolio/south-jerrabomberra-cafe-tenancy-interior-3d-render.webp", title: "South Jerrabomberra Café Tenancy", place: "South Jerrabomberra, NSW", type: "Café interior render", alt: "Photorealistic 3D render of a café tenancy at South Jerrabomberra Town Centre with a timber service counter, bakery display, pendant lighting, indoor trees and customer seating", description: "Hospitality interior visualisation for a café tenancy at South Jerrabomberra Town Centre, featuring a warm timber counter, bakery merchandising, integrated planting and an active customer experience.", keywords: "South Jerrabomberra Town Centre cafe render, hospitality interior 3D rendering, bakery visualisation NSW, cafe fitout CGI, retail architectural visualisation Australia", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/prahran-market-landscaped-courtyard-3d-render.webp", title: "Prahran Market Courtyard", place: "Prahran, VIC", type: "Hospitality courtyard render", alt: "Photorealistic 3D render of the landscaped hospitality courtyard at Prahran Market with abundant planting, outdoor dining, striped seating and a feature illuminated arbour", description: "Hospitality and public-realm visualisation for Prahran Market, showing a lush landscaped courtyard with outdoor dining terraces, layered planting and a central illuminated garden arbour.", keywords: "Prahran Market courtyard 3D render, Melbourne hospitality visualisation, landscaped dining precinct CGI, outdoor restaurant rendering, retail public realm visualisation Victoria", width: 2000, height: 1500, format: "image/webp" },
  { src: "/portfolio/south-jerrabomberra-supermarket-retail-interior-3d-render.webp", title: "South Jerrabomberra Supermarket", place: "South Jerrabomberra, NSW", type: "Supermarket interior render", alt: "Photorealistic 3D render of a supermarket at South Jerrabomberra Town Centre with fresh produce displays, refrigerated aisles, suspended planting and shoppers", description: "Retail interior visualisation for the South Jerrabomberra Town Centre supermarket, communicating fresh-food merchandising, aisle layout, lighting, planting and customer circulation.", keywords: "South Jerrabomberra supermarket render, grocery retail 3D visualisation, supermarket interior CGI NSW, retail fitout rendering, shopping centre visualisation Australia", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/king-square-gym-workout-space-3d-render.webp", title: "King Square Gym", place: "Australia", type: "Fitness interior render", alt: "Photorealistic 3D render of the King Square gym with strength and cardio equipment, full-height glazing, mirrored walls and a sculptural wave ceiling", description: "Fitness and wellness interior visualisation for King Square, presenting equipment planning, circulation, natural light, mirrored finishes and the feature undulating ceiling.", keywords: "King Square gym 3D render, fitness centre interior visualisation, commercial gym CGI Australia, wellness space rendering, leisure fitout visualisation", width: 2048, height: 1536, format: "image/webp" },
  { src: "/portfolio/horrex-road-ravensbourne-function-room-3d-render.webp", title: "Ravensbourne Function Room", place: "Ravensbourne, QLD", type: "Event venue render", alt: "Photorealistic 3D render of a function room on Horrex Road in Ravensbourne set for a formal event with round tables, floral arrangements, timber ceiling and stone flooring", description: "Hospitality venue visualisation for a function room on Horrex Road, Ravensbourne, showing the event layout, table settings, warm timber ceiling, natural stone floor and garden outlook.", keywords: "Horrex Road Ravensbourne function room render, Queensland event venue 3D visualisation, wedding venue CGI, hospitality interior rendering, function centre architectural visualisation", width: 2048, height: 1364, format: "image/webp" },
] as const;

export const servicePortfolioProjects: Readonly<Record<string, readonly PortfolioProject[]>> = {
  "residential-3d-rendering": residentialProjects,
  "facade-renders": facadeProjects,
  "commercial-3d-rendering": commercialProjects,
  "photomontage-rendering": photomontageProjects,
  "marketing-floor-plans": marketingFloorPlanProjects,
  "property-marketing-cgi": independentSelection(),
  "streetscape-renders": streetscapeProjects,
  "living-kitchen-dining-renders": livingKitchenDiningProjects,
  "alfresco-backyard-renders": alfrescoBackyardProjects,
  "industrial-visualisation": industrialProjects,
  "office-fit-out-renders": officeFitoutProjects,
  "retail-hospitality-renders": retailHospitalityProjects,
  "education-childcare-renders": independentSelection(),
  "3d-site-master-plans": independentSelection(),
  "colour-concept-renders": independentSelection(),
};

type SelectedWorksProps = {
  projects?: readonly PortfolioProject[];
};

export default function SelectedWorks({ projects: selectedProjects = projects }: SelectedWorksProps) {
  return (
    <section className="portfolio section" id="work">
      <div className="section-head">
        <div><p className="eyebrow">Selected work</p><h2>Built in pixels.<br /><em>Believed in reality.</em></h2></div>
        <p>A selection of residential and property visualisation projects delivered for clients across Australia.</p>
      </div>
      <div className="project-grid">
        {selectedProjects.map((project, i) => (
          <article className={i === 0 || i === 3 ? "project wide" : "project"} key={project.src} itemScope itemType="https://schema.org/ImageObject">
            <div className="project-image">
              <img src={project.src} alt={project.alt} title={project.description} width={project.width} height={project.height} loading={i > 1 ? "lazy" : "eager"} itemProp="contentUrl" />
              <span className="project-brand-mark" aria-hidden="true">3D</span>
            </div>
            <meta itemProp="description" content={project.description} />
            <meta itemProp="keywords" content={project.keywords} />
            <meta itemProp="encodingFormat" content={project.format} />
            <div className="project-meta"><div><h3 itemProp="name">{project.title}</h3><p itemProp="contentLocation">{project.place}</p></div><span>{project.type}</span></div>
          </article>
        ))}
      </div>
    </section>
  );
}
